name: webview
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  webview_flutter: ^4.0.1
  timeago: ^3.3.0
  http: ^0.13.5
  cached_network_image: ^3.2.3
  animated_stack: ^0.2.0
  
  # pull_to_refresh: ^2.0.0

dev_dependencies: 
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21  

flutter: 
  uses-material-design: true

